#!/usr/bin/env python3
"""
Academic PDF Renamer 

Tired of PDFs named "3687052.pdf" or "JOHN_DOE_University_Conference.pdf"?
This script automatically extracts the actual paper title from your academic PDFs 
and renames them to something meaningful.

What This Script Does:
- Extracts the real paper title from inside the PDF (not just author names!)
- Filters out author and affiliation lines (University, location names, etc.)
- Skips metadata like URLs, dates, conference info, and DOI numbers
- Uses smart scoring to find the most likely title line
- Handles ACM, IEEE, and other academic paper formats
- Prefers lines with colons and question marks (common in research titles)
- Won't rename files that already have good descriptive names

Usage:
1. Install PyPDF2: pip3 install PyPDF2
2. Copy this script into your folder containing PDF files
3. Run: python3 rename_papers.py
4. The script will rename all PDFs in the current directory

Code generated by Claude (Anthropic), verified and curated by the author.
License: MIT
"""

import PyPDF2
import re
import os
from pathlib import Path

# CONFIGURATION
FOLDER_PATH = "."  # Current directory - processes all PDFs where the script is located
MAX_FILENAME_LENGTH = 120
MIN_TITLE_LENGTH = 15

def clean_filename(text):
    """Clean text to be safe for use as filename."""
    # Remove invalid filename characters
    text = re.sub(r'[<>:"/\\|?*]', '', text)
    # Replace multiple spaces with single space
    text = re.sub(r'\s+', ' ', text).strip()
    # Limit length
    return text[:MAX_FILENAME_LENGTH]

def is_author_or_affiliation_line(line):
    """Check if a line is likely an author name or affiliation."""
    # Common patterns in author/affiliation lines
    author_patterns = [
        r'University',
        r'Institut',
        r'College',
        r'Department',
        r'Laboratory',
        r'Netherlands',
        r'USA',
        r'UK',
        r'China',
        r'Japan',
        r'Germany',
        r'France',
        r'Canada',
        r'Australia',
        r'Switzerland',
        r'Belgium',
        r'Denmark',
        r'Sweden',
        r'Norway',
        r',\s*[A-Z][a-z]+,\s*[A-Z]',  # Location patterns
        r'@',
        r'\.edu',
        r'\.com',
        r'Conference',
        r'Proceedings',
        r'ACM',
        r'IEEE',
        r'Published:',
        r'Citation',
        r'Total Downloads',
        r'Total Citations',
        r'Virtual Event',
        r'Lyon, France',
        r'WWW \'',  # WWW '22 etc
    ]
    
    # Check against patterns
    for pattern in author_patterns:
        if re.search(pattern, line, re.IGNORECASE):
            return True
    
    # Check if line has too many commas (typical of affiliations)
    if line.count(',') >= 2:
        return True
    
    return False

def extract_paper_title(pdf_path):
    """Extract title from PDF using multiple strategies."""
    try:
        with open(pdf_path, 'rb') as file:
            reader = PyPDF2.PdfReader(file)
            
            # Strategy 1: Try PDF metadata first
            if reader.metadata and reader.metadata.title:
                title = reader.metadata.title.strip()
                if len(title) > MIN_TITLE_LENGTH and not is_author_or_affiliation_line(title):
                    return clean_filename(title)
            
            # Strategy 2: Extract from first page content
            first_page = reader.pages[0].extract_text()
            lines = [line.strip() for line in first_page.split('\n') if line.strip()]
            
            # Look for title patterns in first 20 lines
            potential_titles = []
            
            for i, line in enumerate(lines[:20]):
                # Skip if it looks like author/affiliation
                if is_author_or_affiliation_line(line):
                    continue
                
                # Filter out short lines, page numbers, URLs, and headers
                if (len(line) > MIN_TITLE_LENGTH and 
                    len(line) <= 200 and
                    not re.match(r'^\d+$', line) and  # Skip page numbers
                    not re.match(r'^[A-Z\s\-]{3,}$', line) and  # Skip ALL CAPS headers
                    not re.match(r'^RESEARCH-ARTICLE', line, re.IGNORECASE) and  # Skip article type
                    not re.search(r'[a-z]+://', line, re.IGNORECASE) and  # Skip lines with URLs (any protocol)
                    not re.search(r'dl\.acm\.org', line, re.IGNORECASE) and  # Skip ACM URLs
                    not re.match(r'^doi:', line, re.IGNORECASE) and  # Skip DOIs
                    not re.match(r'^abstract', line, re.IGNORECASE) and  # Skip "Abstract"
                    not re.match(r'^latest update', line, re.IGNORECASE) and  # Skip "Latest updates"
                    not re.match(r'^download', line, re.IGNORECASE) and  # Skip "Download"
                    not re.match(r'^pdf download', line, re.IGNORECASE) and  # Skip "PDF Download"
                    not re.match(r'^open access', line, re.IGNORECASE) and  # Skip "Open Access"
                    not re.search(r'ISBN', line, re.IGNORECASE) and  # Skip ISBN lines
                    not re.search(r'(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2}', line, re.IGNORECASE) and  # Skip dates
                    not re.search(r'\d{4}\.\d{4}', line)):  # Skip DOI numbers like 3485447.3512040
                    
                    # Calculate a score for this line
                    score = 0
                    
                    # Prefer lines with colons (often in titles)
                    if ':' in line:
                        score += 50
                    
                    # Prefer lines that start with capital letters
                    if line[0].isupper():
                        score += 20
                    
                    # Prefer medium-length lines (50-150 chars)
                    if 50 <= len(line) <= 150:
                        score += 30
                    elif 30 <= len(line) <= 200:
                        score += 10
                    
                    # Penalize very long lines
                    if len(line) > 150:
                        score -= 20
                    
                    # Prefer earlier lines (but not the first 2, which might be headers)
                    if 2 <= i <= 5:
                        score += 15
                    elif i > 10:
                        score -= 10
                    
                    # Bonus for lines with question marks (common in research titles)
                    if '?' in line:
                        score += 25
                    
                    potential_titles.append((score, len(line), line, i))
            
            # Sort by score (highest first), then length, then position
            potential_titles.sort(key=lambda x: (-x[0], -x[1], x[3]))
            
            if potential_titles:
                return clean_filename(potential_titles[0][2])
            
            # Strategy 3: Fallback to first substantial non-author line
            for line in lines[:15]:
                if (MIN_TITLE_LENGTH <= len(line) <= 200 and 
                    not is_author_or_affiliation_line(line)):
                    return clean_filename(line)
                    
    except Exception as e:
        print(f"Error reading {pdf_path}: {e}")
    
    return None

def is_already_renamed(filename):
    """Check if file already has a descriptive name."""
    stem = Path(filename).stem
    
    # If the filename itself looks like an author/affiliation, it needs renaming
    if is_author_or_affiliation_line(stem):
        return False
    
    # Skip if filename is long and doesn't look like random characters
    return (len(stem) > 50 and 
            not re.match(r'^[a-f0-9\-_]+$', stem.lower()) and
            not re.match(r'^(document|paper|file)\d*$', stem.lower()))

def rename_academic_pdfs(folder_path):
    """Main function to rename PDFs in specified folder."""
    folder = Path(folder_path)
    
    if not folder.exists():
        print(f"Error: Folder '{folder_path}' doesn't exist!")
        print("Please update the FOLDER_PATH variable in the script.")
        return
    
    pdf_files = list(folder.glob("*.pdf"))
    
    if not pdf_files:
        print(f"No PDF files found in '{folder_path}'")
        return
    
    print(f"Found {len(pdf_files)} PDF files")
    print("-" * 50)
    
    renamed_count = 0
    skipped_count = 0
    
    for pdf_file in pdf_files:
        print(f"\nProcessing: {pdf_file.name}")
        
        # Skip if already has descriptive name
        if is_already_renamed(pdf_file.name):
            print("  → Skipping (already has descriptive name)")
            skipped_count += 1
            continue
        
        # Extract title
        title = extract_paper_title(pdf_file)
        
        if not title:
            print("  ✗ Could not extract title")
            continue
        
        # Check if new title is meaningfully different
        if title.lower() == pdf_file.stem.lower():
            print("  → Title same as current filename, skipping")
            skipped_count += 1
            continue
        
        # Handle potential filename conflicts
        new_name = f"{title}.pdf"
        new_path = pdf_file.parent / new_name
        
        counter = 1
        base_title = title
        while new_path.exists() and new_path != pdf_file:
            title = f"{base_title}_{counter}"
            new_name = f"{title}.pdf"
            new_path = pdf_file.parent / new_name
            counter += 1
        
        # Rename the file
        try:
            pdf_file.rename(new_path)
            print(f"  ✓ Renamed to: {new_name}")
            renamed_count += 1
        except Exception as e:
            print(f"  ✗ Error renaming: {e}")
    
    print("\n" + "=" * 50)
    print(f"SUMMARY:")
    print(f"  Renamed: {renamed_count} files")
    print(f"  Skipped: {skipped_count} files")
    print(f"  Total processed: {len(pdf_files)} files")

def main():
    """Entry point of the script."""
    print("Academic PDF Renamer - IMPROVED VERSION")
    print("=" * 50)
    print(f"Processing PDFs in: {os.path.abspath(FOLDER_PATH)}")
    print()
    
    rename_academic_pdfs(FOLDER_PATH)

if __name__ == "__main__":
    main()